AWSTemplateFormatVersion: '2010-09-09'
Description: Full Textract Pipeline - Cleaned Version

Resources:
  # 1. THE QUEUE
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 90 # Increased to give Lambda more time

  # 2. THE QUEUE POLICY
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref ProcessingQueue]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: s3.amazonaws.com }
            Action: sqs:SendMessage
            Resource: !GetAtt ProcessingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub "arn:aws:s3:::textract-uploads-${AWS::AccountId}"

  # 3. THE BUCKET
  DocumentBucket:
    Type: AWS::S3::Bucket
    DependsOn: QueuePolicy
    Properties:
      # Using a very unique name to avoid collisions
      BucketName: !Sub "textract-data-drop-${AWS::AccountId}"
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ProcessingQueue.Arn

  # 4. THE TABLE
  ResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "TextractResults-${AWS::StackName}"
      AttributeDefinitions:
        - AttributeName: DocumentId
          AttributeType: S
      KeySchema:
        - AttributeName: DocumentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 5. THE ROLE (Added a slight delay/dependency helper)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonTextractFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  # 6. THE LAMBDA (Removed manual FunctionName)
  TextractProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import boto3
          def handler(event, context):
              print("Ready to process Textract!")
              return {'statusCode': 200}

  # 7. THE TRIGGER
  LambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt ProcessingQueue.Arn
      FunctionName: !Ref TextractProcessorFunction